"""Markdown report rendering for Phase 3 vulnerability results."""

from __future__ import annotations

from app.schemas.agent_result_schema import AgentResult
from app.schemas.enum_schema import EnumInput
from app.schemas.vuln_schema import Severity, VulnerabilityOutput


def render_markdown_report(
    output: VulnerabilityOutput,
    enum_input: EnumInput,
    agent_results: tuple[AgentResult, ...],
) -> str:
    """Render a structured Markdown report for an authorized scan."""

    lines = [
        f"# Phase 3 Vulnerability Report: {output.scan_id}",
        "",
        "## Executive Summary",
        "",
        (
            f"The authorized Phase 3 scan produced {output.summary.total} "
            "normalized findings."
        ),
        "",
        "## Scope",
        "",
        f"- Scan ID: {enum_input.scan_id}",
        f"- Target label: {enum_input.target}",
        f"- Declared scope: {enum_input.scope or 'N/A'}",
        f"- Generated by: {enum_input.generated_by or 'N/A'}",
        (
            f"- Created at: {enum_input.created_at.isoformat()}"
            if enum_input.created_at is not None
            else "- Created at: N/A"
        ),
        f"- Authorized hosts: {', '.join(str(host.ip) for host in enum_input.hosts)}",
        "- Public Internet scanning: blocked",
        "",
        "## OS Inventory",
        "",
    ]

    for host in enum_input.hosts:
        lines.append(f"### {host.ip}")
        lines.append("")
        if host.os is None:
            lines.append("OS fingerprint: Not provided.")
        else:
            lines.extend(
                [
                    f"- Hostname: {host.hostname or 'N/A'}",
                    f"- Vhosts: {', '.join(host.vhosts) or 'N/A'}",
                    f"- Name/version: {_os_name_version(host.os.name, host.os.version)}",
                    f"- Kernel: {host.os.kernel or 'N/A'}",
                    f"- Build: {host.os.build or 'N/A'}",
                    f"- Architecture: {host.os.architecture or 'N/A'}",
                    f"- CPE: {', '.join(host.os.cpe) or 'N/A'}",
                    (
                        f"- Confidence: {host.os.confidence:.2f}%"
                        if host.os.confidence is not None
                        else "- Confidence: N/A"
                    ),
                    f"- Source: {host.os.source or 'N/A'}",
                ]
            )
        lines.append("")

    lines.extend(
        [
        "## Enumeration Inventory",
        "",
        ]
    )

    for host in enum_input.hosts:
        lines.extend(
            [
                f"### {host.ip} ({host.hostname or 'hostname N/A'})",
                "",
                f"- Vhosts: {', '.join(host.vhosts) or 'N/A'}",
                "",
            ]
        )
        for port in host.ports:
            lines.extend(
                [
                    f"#### {port.port}/{port.protocol} {port.service}",
                    "",
                    f"- State: {port.state or 'N/A'}",
                    f"- Product/version: {_os_name_version(port.product, port.version)}",
                    f"- Banner: {port.banner or 'N/A'}",
                    f"- CPE: {', '.join(port.cpe) or 'N/A'}",
                    f"- Source: {port.source or 'N/A'}",
                    (
                        f"- Confidence: {port.confidence:.2f}%"
                        if port.confidence is not None
                        else "- Confidence: N/A"
                    ),
                    f"- URL: {str(port.url) if port.url is not None else 'N/A'}",
                    f"- Vhost: {port.vhost or 'N/A'}",
                    f"- Technologies: {', '.join(port.technologies) or 'N/A'}",
                    f"- Discovered paths: {', '.join(port.discovered_paths) or 'N/A'}",
                    f"- API endpoints: {', '.join(port.api_endpoints) or 'N/A'}",
                    "",
                ]
            )
        if host.web:
            lines.append("#### Web Surfaces")
            lines.append("")
            for web in host.web:
                lines.extend(
                    [
                        f"- URL: {web.url}",
                        f"- Product/version: {_os_name_version(web.product, web.version)}",
                        f"- Title: {web.title or 'N/A'}",
                        f"- Banner: {web.banner or 'N/A'}",
                        f"- Vhost: {web.vhost or 'N/A'}",
                        f"- Technologies: {', '.join(web.technologies) or 'N/A'}",
                        f"- Interesting paths: {', '.join(web.interesting_paths) or 'N/A'}",
                        f"- API endpoints: {', '.join(web.api_endpoints) or 'N/A'}",
                        "",
                    ]
                )

    lines.extend(
        [
        "## Findings by Severity",
        "",
        "| Severity | Count |",
        "| --- | ---: |",
        f"| Critical | {output.summary.critical} |",
        f"| High | {output.summary.high} |",
        f"| Medium | {output.summary.medium} |",
        f"| Low | {output.summary.low} |",
        f"| Info | {output.summary.info} |",
        "",
        "## Technical Details",
        "",
        ]
    )

    if not output.findings:
        lines.append("No findings were produced.")
    for finding in output.findings:
        lines.extend(
            [
                f"### {finding.title}",
                "",
                f"- CVE ID: {finding.cve_id or finding.finding_id}",
                f"- Template ID: {finding.template_id or 'N/A'}",
                f"- Host: {finding.host or 'N/A'}",
                f"- Port: {finding.port or 'N/A'}",
                f"- Severity: {finding.severity.value}",
                f"- CVSS: {finding.cvss if finding.cvss is not None else 'N/A'}",
                f"- Confidence: {finding.confidence:.2f}",
                f"- Match method: {finding.match_method or 'N/A'}",
                f"- Validation required: {'yes' if finding.validation_required else 'no'}",
                f"- Risk score: {finding.risk_score:.2f}",
                f"- Source type: {finding.source_type.value}",
                f"- Source agents: {', '.join(finding.source_agents) or 'N/A'}",
                f"- Evidence: {finding.evidence}",
                f"- References: {', '.join(finding.references) or 'N/A'}",
                "",
            ]
        )

    lines.extend(["## Remediation", ""])
    if not output.findings:
        lines.append("No remediation actions are required from this scan.")
    for finding in output.findings:
        lines.append(f"- **{finding.title}:** {finding.remediation}")

    lines.extend(["", "## Appendix", "", "### Agent Status", ""])
    lines.extend(
        f"- `{result.agent_name}`: {result.status.value}"
        + (f" - {result.message}" if result.message else "")
        for result in agent_results
    )
    lines.extend(_nuclei_runtime_notes(agent_results))
    lines.extend(
        [
            "",
            "### Methodology",
            "",
            "Findings were deduplicated by host, port, CVE ID, title, and "
            "source type. Severity was normalized from standard CVSS ranges. "
            "Risk scores were calculated from CVSS and confidence, with a "
            "capped bonus for Nuclei confirmation.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def _os_name_version(name: str | None, version: str | None) -> str:
    values = [value for value in (name, version) if value]
    return " ".join(values) if values else "N/A"


def _nuclei_runtime_notes(agent_results: tuple[AgentResult, ...]) -> list[str]:
    for result in agent_results:
        if result.agent_name != "nuclei_agent":
            continue

        data = result.data
        mode = data.get("execution_mode")
        matched_count = data.get("matched_count")
        used_mock_fallback = bool(data.get("used_mock_fallback"))

        if mode == "cli" and result.status.value == "success" and matched_count == 0:
            return [
                "",
                "### Nuclei Runtime",
                "",
                "- Nuclei CLI completed with 0 critical/high matches.",
            ]
        if mode == "mock":
            fixture_label = "fallback/offline fixture" if used_mock_fallback else "offline fixture"
            return [
                "",
                "### Nuclei Runtime",
                "",
                f"- Nuclei used {fixture_label} mode.",
            ]
    return []
